# Generated by Django 3.1.13 on 2022-01-17 03:48

import Tutors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('source_id', models.TextField(db_index=True, editable=False, max_length=60)),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=Tutors.models.imagelocation)),
            ],
        ),
    ]
