# Generated by Django 3.1.13 on 2021-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_id',
            field=models.TextField(editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.TextField(editable=False, max_length=60),
        ),
    ]
