# Generated by Django 3.1.13 on 2021-11-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutors', '0002_auto_20211111_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_id',
            field=models.TextField(db_index=True, editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='area',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='Tutors.tutor', to_field='tutor_id'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.TextField(db_index=True, editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_id',
            field=models.CharField(db_index=True, editable=False, max_length=10, unique=True),
        ),
    ]
