# Generated by Django 3.1.13 on 2021-11-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutors', '0004_auto_20211111_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Tutors.tutor', to_field='tutor_id'),
        ),
    ]
